<div class="row g-3">
    <div class="col-12"><label class="form-label">Judul artikel</label><input name="title" value="{{ old('title', $article->title ?? '') }}" class="form-control" required maxlength="255"></div>
    <div class="col-md-4"><label class="form-label">Kategori</label><input name="category" value="{{ old('category', $article->category ?? 'Logistics') }}" class="form-control" list="articleCategories" required maxlength="60"><datalist id="articleCategories"><option value="Logistics"><option value="Shipping"><option value="Trade"><option value="Economy"><option value="Geopolitics"><option value="Risk Analysis"></datalist></div>
    <div class="col-md-4"><label class="form-label">Sentimen</label><select name="sentiment" class="form-select" required>@foreach(['Positive','Neutral','Negative'] as $sentiment)<option value="{{ $sentiment }}" @selected(old('sentiment', $article->sentiment ?? 'Neutral') === $sentiment)>{{ $sentiment }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Status publikasi</label><select name="status" class="form-select" required><option value="draft" @selected(old('status', $article->status ?? 'draft') === 'draft')>Draft</option><option value="published" @selected(old('status', $article->status ?? '') === 'published')>Published</option></select></div>
    <div class="col-12"><label class="form-label">Ringkasan</label><textarea name="summary" rows="3" maxlength="1000" class="form-control" placeholder="Ringkasan singkat hasil analisis...">{{ old('summary', $article->summary ?? '') }}</textarea></div>
    <div class="col-12"><label class="form-label">Isi analisis</label><textarea name="content" rows="12" class="form-control" required placeholder="Tuliskan data, interpretasi, risiko, dan rekomendasi...">{{ old('content', $article->content ?? '') }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Waktu publikasi (opsional)</label><input name="published_at" type="datetime-local" value="{{ old('published_at', isset($article) && $article->published_at ? $article->published_at->format('Y-m-d\TH:i') : '') }}" class="form-control"><small class="text-secondary">Jika status Published dan kosong, sistem memakai waktu saat ini.</small></div>
</div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-info fw-semibold"><i class="bi bi-save me-1"></i>Simpan Artikel</button><a href="{{ route('admin.articles.index') }}" class="btn btn-outline-secondary">Batal</a></div>
